- docs/Changelog.rst
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR updates the style and markup of the default templates.
It also fixes a rendering problem with the multi-default template
--
> Updated default report templates

- docs/Changelog.rst
- src/senaite/impress/publishview.py
Linked issue: https://github.com/senaite/senaite.impress/issues/4
Content overflow in A4 landscape, because the default margins are there different for top/bottom and left/right.
Correct content layout for all formats and margins
--
> Correct margin calculation

- docs/Changelog.rst
- src/senaite/impress/static/css/print.css
This PR updates the default `print.css`, so that page breaks are avoided within rows and contents are allowed to overflow over the calculated content size.
--
> Better Print CSS

- docs/Changelog.rst
- src/senaite/impress/configure.zcml
- src/senaite/impress/profiles/default/metadata.xml
- src/senaite/impress/profiles/uninstall/metadata.xml
- src/senaite/impress/upgrades/__init__.py
- src/senaite/impress/upgrades/configure.zcml
- src/senaite/impress/upgrades/handlers.py
This PR adds the upgrade step machinery to `senaite.impress` and starts over with the profile version 1000.
No upgrade step machinery integrated
Upgrade step machinery integrated
--
> Added upgrade-step machinery

- src/senaite/impress/static/css/bootstrap-print.css
This PR removes the CSS style for `.col` which was introduced in #13 because of side-effects with  existing reports
--
> Removed generic column CSS style

- docs/Changelog.rst
- src/senaite/impress/emailview.py
This PR handles commas in the recipient names better for email usage
commas in given- or surname were incorrect splitted
commas in given- or surname are correctly splitted
--
> Handle commas in recipient email name better

- docs/Changelog.rst
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR adds special HTML markup for the report alert section 
Alerts overlapped the header section
Alerts do not overlap header section
--
> Fix alert section overlapping of the header section

- docs/Changelog.rst
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR fixes the rendering of barcodes in the multi column report
Barcodes are displayed next to each other without spaces in between
Barcodes are displayed below each other and aligned right
--
> Fixed barcode rendering in multi-colum report

- docs/Changelog.rst
- src/senaite/impress/templates/email_template.pt
This PR removes the leading whitespaces of the email template and added the sentence:
`*** This is an automatically generated email, please do not reply to this message. ***`
--
> Improved email template

- docs/Changelog.rst
- src/senaite/impress/ajax.py
- src/senaite/impress/controlpanel.py
- src/senaite/impress/publishview.py
This PR introduces a setting to control whether a multi-report PDF should be generated for all all the contained ARs or only for the primary AR.
Multi report PDFs get stored for all contained ARs individually.
Multi report PDFs get stored either for all contained ARs individually, or only for the primary AR of the multi-report only.
--
> Control individual report generation for multi-report PDFs

- docs/Changelog.rst
- src/senaite/impress/controlpanel.py
This PR adds some descriptions to the controlpanel fields
Missing field descriptions
Fields have proper descriptions
--
> Added controlpanel descriptions

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/configure.zcml
- src/senaite/impress/analysisrequest/reportview.py
- src/senaite/impress/publishview.py
- src/senaite/impress/reportview.py
This allows 3rd party Add-ons to override the adapter with a specific browser
layer interface like this:
<adapter
for="zope.interface.Interface
my.addon.interfaces.IMyAddonLayerInterface"
name="AnalysisRequest"
factory=".reportview.SingleReportView"
provides="senaite.impress.interfaces.IReportView"
permission="zope2.View"/>
Add-on specific report controller views could not be registered
Add-on specific report controller views can be registered
--
> Refactored Report Adapters to Multi Adapters

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/reportview.py
This PR fixes the domain from `bika` to `senaite.core`
--
> Fixed i18n domain for time localization

- docs/Changelog.rst
- src/senaite/impress/ajax.py
- src/senaite/impress/controlpanel.py
- src/senaite/impress/publishview.py
This PR adds a control-panel option to enable/disable the developer mode.
With the developer mode turned on, the report will be returned as plain HTML.
This allows the report designer to quickly render the report and being able to introspect the HTML.
No developer mode available
Developer mode available
--
> Added report developer mode

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/reportview.py
This PR ensures the order of grouped items
grouped items order not kept
grouped items keep initial order
--
> Keep order of grouped items

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/reportview.py
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR fixes the sort order of uniquified items, e.g. the Analyses Titles in the Multi-Default-By-Column Report.
`set` is used to uniquify the items, which does not maintain the sort order of the list
`view.uniquify_items` method is used, which maintains the sort order of the imtes
--
> Fix sort order of uniquified items

- src/senaite/impress/javascripts.py
- src/senaite/impress/templates/publish.pt
This PR ensures that only uncooked JS resources are used in the publish view.
Cooked (merged) JS resources were used in the publish view
Unmerged JS libraries are used in the publish view
--
> Include uncooked JS resources from portal_javascripts

- src/senaite/impress/analysisrequest/reportview.py
- src/senaite/impress/publishview.py
Propagate orientation to page template
Support SuperModel in get_transition_date method
--
> Added some auxiliary code

- docs/Changelog.rst
- src/senaite/impress/config.py
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR updates all default reports to include a custom report option for the "attachments per row", a sample JS snippet with the available report options, corrected CSS and new markup.
--
> Default reports update

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/model.py
- src/senaite/impress/analysisrequest/reportview.py
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR combines the AR/AN Attachments per AR in the reports, so that the sorting applies correctly.
AR Attachments were rendered separately from AN Attachments
AR and AN Attachments are rendered combined in reports
--
> Combine Attachments coming from Request and Analysis together for unified grouping/sorting

- docs/Changelog.rst
- setup.py
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR integrates the latest changes from https://github.com/senaite/senaite.core/pull/1027 into impress and pins `senaite.core` to `>=1.2.9`.
`ChildAnalysisRequest` field was used
`Retest` field is used
--
> Changed field ChildAnalysisRequest -> Retest

- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This PR updates the markup/style to better handle large images in attachments/results interpretation
--
> Update Template Markup/Style

- docs/Changelog.rst
- src/senaite/impress/ajax.py
This PR fixes the PDF storage to the primary AR when the option "Store Multi-Report PDFs Individually" is turned off.
The last AR was used to store the PDF
The primary AR is used to store the PR 
--
> Fix PDF storage in primary AR when "Store Multi-Report PDFs Individually" option is turned off.

- src/senaite/impress/analysisrequest/model.py
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
Traceback when rendering the report with `senaite.core` >=1.3.0
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module senaite.impress.decorators, line 41, in decorator
Module senaite.impress.ajax, line 64, in __call__
Module senaite.impress.ajax, line 175, in ajax_render_reports
Module senaite.impress.publishview, line 189, in render_multi_report
Module senaite.impress.publishview, line 306, in read_template
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 98, in __call__
Module z3c.pt.pagetemplate, line 158, in render
Module chameleon.zpt.template, line …
```
> Traceback because of getRetested attribute

- setup.py
Pin versions
No version pinnings
- Pinned version of `senaite.core` >= 1.3.0
- Pinned version of `WeasyPrint` == 0.42.3
- Pinned version of `senaite.core.supermodel` >= 1.1.0 
--
> Pinned versions

- docs/Changelog.rst
- src/senaite/impress/ajax.py
This PR supersedes https://github.com/senaite/senaite.impress/pull/48
The issue here is that the primary AR for storage was determined by the order in which the ARs appear in the report. This differs depending on the template, e.g. the primary appears on top (first position) for multi-reports, but on the most right (last  position) for multi-by-column templates.
Primary AR determined by the order in which they appear in the Report.
Primary AR is always the most recent one depending on the created date
--
> Use most recent AR as primary storage

- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
This Pull Request is meant to include all changes required to make `senaite.impress` compatible with `senaite.core` v1.3.0.
- Unbount reports from Sample portal type. 
Requirement: [#1180 Sample clenaup](https://github.com/senaite/senaite.core/pull/1180)
`senaite.impress` not compatible with `senaite.core` v1.3.0
`senaite.impress` compatible with `senaite.core` v1.3.0
--
> Integration with senaite.core v1.3

- docs/Changelog.rst
- src/senaite/impress/analysisrequest/reportview.py
https://github.com/senaite/senaite.impress/issues/64
By default, rejected analyses are displayed in results reports
By default, rejected analyses are not displayed in results reports
--
> Rejected AS are shown in the PDF Report

- docs/Changelog.rst
- src/senaite/impress/templates/reports/Default.pt
Traceback is rised when Default template is selected in report preview.
https://github.com/senaite/senaite.impress/issues/66
```
Error: PublicationPreference
- Expression: "python:contact and contact.PublicationPreference != '' and 'email' in contact.PublicationPreference"
- Filename:   ... impress/src/senaite/impress/templates/reports/Default.pt
- Location:   (line 627: col 28)
- Source:     ... python:contact and contact.PublicationPreference != '' and 'email' in contact.PublicationPreference ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
- Arguments:  page_width: 210.0
request: <instance - at 0x7f99e1661f38>
laboratory: <SuperModel - at 0x7f99de5d3710>
content_height: 257.0
container: <ImplicitAcquisitionWrapper senaite at …
```
> Fix PublicationPreference Traceback in Default template

- README.md
- docs/Changelog.rst
Added more details to the 'Reports in external packages' section of the READ
--
> Extend 'Reports in external packages' section of README

- docs/Changelog.rst
- src/senaite/impress/decorators.py
- src/senaite/impress/publisher.py
- src/senaite/impress/storage.py
This PR improves the report creation process for simultaneous publications.
Conflict errors occur for simultaneous report publications. E.g. pressing the "Save" button for 20 rendered previews quickly one-by-one.
No conflict errors occur for simultaneous report publications
--
> Conflict safe concurrent report creation

- src/senaite/impress/analysisrequest/reportview.py
Depends on: https://github.com/senaite/senaite.core/pull/1391
With this Pull Request, analyses marked with `IInternalUse` are not displayed in results reports. Consider the following scenario:
- Client contact creates a new Sample
- Lab received the Sample and create two partitions
- One of the partitions is labelled for internal use (with additional analyses or for storage, etc.)
Without this Pull Request, when LabMan generates a report for the Primary Sample, analyses from the sample labeled as for internal use will be displayed.
All analyses of a given Sample are displayed in results report
Analyses marked with "IInternalUse" interface are not displayed in results report
--
and [Plone's Python styleguide][2] …
> Do not display Analyses marked for InternalUse in results report

- docs/Changelog.rst
- src/senaite/impress/templates/reports/Default.pt
- src/senaite/impress/templates/reports/MultiDefault.pt
- src/senaite/impress/templates/reports/MultiDefaultByColumn.pt
Fix error in report footer when no lab address is given.
Templates are displayed correctly, even when some lab data is missing
--
> Fix template error on missing lab address data

- docs/Changelog.rst
- src/senaite/impress/templates/reports/MultiDefault.pt
Linked issue: https://github.com/senaite/senaite.impress/issues/68
Date published empty in MultiDefault report 
Date published uses current timestamp in MultiDefault report 
--
> Fix Date Published is empty on MultiDefault report

- src/senaite/impress/publishview.py
This PR fixes an occasional encoding issue when printing (via `printview` PDF button) a report that contains unicode characters, e.g. german umlauts `äöü`.
Unicode characters are not printed correctly in the PDF
Unicode characters are printed correctly in the PDF
--
> Fix HTML encoding for PDF printing
